### PR TITLE
Adds a Getting Started Article for VSCode

### PR DESCRIPTION
**Pull request by AristurtleDev**
## Description
This PR adds a getting started article for setting up a development environment for to use MonoGame with VSCode. The article contains instructions for Windows, macOS, and Linux, each separated using the tabs feature.

## Live Preview
A live preview of the article can be found at [https://mgdocs.aristurtle.net/articles/getting_started/1_setting_up_your_development_environment_vscode.html](https://mgdocs.aristurtle.net/articles/getting_started/1_setting_up_your_development_environment_vscode.html)

## References
[Issue MonoGame/docs.monogame.github.io#5: feature request: Add Getting started with VS Code article](https://github.com/MonoGame/docs.monogame.github.io/issues/5)

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
PR failing @AristurtleDev ?

**Review by SimonDarksideJ — CHANGES_REQUESTED** [review]
A few comments.

* Needs an "Overview" section at the top, like a TOC, to give a high level overview of the process
* I don't think the VSCode Extensions setup needs all three platforms, as VSCOde makes this the same for all platforms (could not see any differences in your writeup)
* For sections that ONLY apply to Mac/Linux, please state that in the header, e.g "Setup Wine For Effect Compilation - MacOS/Linux only)
* Apple Silicon also needs a note about installing both x64 and x86 workloads, as well as paths and environment settings setup.  And try not to assume any knowledge about Macs (I was a first time user setting up my Mac for MonoGame and it was MANY tutorials before I found the secret sauce)
* Needs a summary for what the reader should have by the end of the guide, as well as the existing link for "where to go next"

**Comment by AristurtleDev** [comment]
> Apple Silicon also needs a note about installing both x64 and x86 workloads, as well as paths and environment settings setup. And try not to assume any knowledge about Macs (I was a first time user setting up my Mac for MonoGame and it was MANY tutorials before I found the secret sauce)

I've asked @dellis1972 if he can update the document with his known fix of using `<DotnetCommand>`.  Or if he can dm me the information I can update that section.

**Review by AristurtleDev — COMMENTED** [review]
Thanks @dellis1972

**Comment by AristurtleDev** [comment]
Should be good for review now @SimonDarksideJ

**Review by SimonDarksideJ — APPROVED** [review]

**Review by SimonDarksideJ — APPROVED** [review]
I abore this change for windows, but ok then :D

**Pull request merged**
