### PR TITLE
Added 2D migrated articles

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
Migrated some of the 2D articles, including the primary 2D "whatis" 2D article

### CODE REVIEW

**Comment by CartBlanche** [comment]
@SimonDarksideJ could we possibly have animations showing the desired result too?

**Comment by SimonDarksideJ** [comment]
As requested @CartBlanche , output images for each sample were added, including animated ones for those that move.

**Comment by CartBlanche** [comment]
@SimonDarksideJ we don't need animations for the Matrix docs, right?

**Comment by SimonDarksideJ** [comment]
The two docs without images are just variants of their base articles, so it feels a little overkill to add to those as well.

**Review by CartBlanche — APPROVED** [review]
LGTM

**Comment by CartBlanche** [comment]
@SimonDarksideJ says it's out of sync with the base branch, so might be worth rebasing.

**Comment by SimonDarksideJ** [comment]
Oh no it isn't 😂
ArisTurtle just fixed the toc's and that needed pulling in, that's all.
Ready for merge again@CartBlanche

**Pull request merged**
